### ISSUE TITLE
Wont run / does nothing

### ISSUE THREAD

**Issue by SuneRadich** [helpers/handlebars-helper-prettify#9]
I am trying to use this helper in my assemble setup. I am quite new to assemble, so bear with me if what I am asking is something I should know :)

In my assemble configuration I have added:

    options: {
        helpers: [
            'handlebars-helpers-prettify'
        ],
        prettify: {
            mode: 'html',  // 'html' is defined by default
            condense: true,
            padcomments: true,
            indent: 40
        },
        flatten: false,        
        partials: ['<%= package.html %>/_partials/**/*.html'],
        layout: '<%= package.html %>/_layouts/main.html'
    },

    pages: {
        files: [
            { 
                expand: true, 
                cwd: '<%= package.html %>/', 
                src: [
                    
                    //All pages and subfolders
                    '**/*.html',
  
                    //except the partials and layouts
                    '!_partials/**',
                    '!_layouts/**'
                ], 
                dest: '<%= package.prototype %>/'
            }
        ]
    }

If I then in a handlebars template use code like this

    {{#prettify}}
        <h1>This is a test</h1><p>Just a test</p>
    {{/prettify}}

I would expect the output from Assemble would be nicely formatted like this:

    <h1>This is a test</h1>
    <p>Just a test</p>

However, it seems the formatting is not changed at all.

If I however then try to do this

    {{#prettify indent="4"}}
        <h1>This is a test</h1><p>Just a test</p>
    {{/prettify}}

My grunt setup fails with:

    Assembling _prototype/components/component.html ERROR
    Warning: ((helpers.prettify || (depth0 && depth0.prettify)) || helpers.helperMissing).call is not a function      Use --force to continue.

It is as if the helper is registered (since the tags `{{#prettify}}` and `{{/prettify}}` are not ignored. What am I doing wrong.

Config from my packages.json

    "grunt-assemble": "^0.4.0",
    "handlebars-helper-prettify": "^0.2.1",

What am I doing wrong?

**Comment by doowb** [comment]
```js
    helpers: [
        'handlebars-helpers-prettify'
    ],
```

Looks like there's an extra `s` on `helper`.  It should be `handlebars-helper-prettify`

The reason you didn't get the error with:

```handlebars
{{#prettify}}
    <h1>This is a test</h1><p>Just a test</p>
{{/prettify}}
```

is because handlebars sees that as a missing variable and just doesn't rendering anything.

When you added the `{{#prettify indent="4"}}` handlebars knows that you were trying to use a helper and throws an error that it cannot find the helper.

**Comment by SuneRadich** [comment]
The dangers of copy pasting :)

Thanks for the explanation, it works as I would imagine it should now.
